export const JOB_ADD_TO_CART = "JOB_ADD_TO_CART";
export const JOB_REMOVE_FROM_CART = "JOB_REMOVE_FROM_CART";
export const JOB_EMPTY_CART = "JOB_EMPTY_CART";
export const JOB_INCREMENT_CARD = "JOB_INCREMENT_CARD";
export const JOB_DECREMENT_CARD = "JOB_DECREMENT_CARD";
